services:
  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db-data:
